### ISSUE TITLE
Build output have extra empty lines on Windows

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell#189]
On latest version of all atom-haskell plug-ins and Atom itself there are empty lines for each build output line on Windows 10. May be the problem is similar to line endings problem in Error/Warning outputs.

**Comment by lierdakil** [comment]
Should be fixed by ide-haskell-cabal v1.7.4

**Comment by varosi** [comment]
The problem remains in 1.7.4.

2017-01-28 10:19 GMT+02:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
I'd like a screenshot, if you could provide one. If it looks somewhat like this:
![image](https://cloud.githubusercontent.com/assets/7275622/22397038/279cf27a-e579-11e6-96ee-15c01f224ef8.png)
that is expected. Some visual margin I find to be useful to differentiate between a wrapped and unwrapped line (could probably make that smaller though)

**Comment by lierdakil** [comment]
Okay, pushed ide-haskell v1.9.1 which makes vertical margins about half the size of what those are now. Should look less sparse.

**Comment by varosi** [comment]
It looks good now! Thanks a lot!

2017-01-28 15:54 GMT+02:00 Nikolay Yakimov <notifications@github.com>:
