### ISSUE TITLE
HTMLElement.rootElement is deprecated.

### ISSUE THREAD

**Issue by shiyah** [atom-haskell/ide-haskell#208]
Atom 1.19.0 release added a new deprecation:
---
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (C:\Users\<USER>\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:23:10)
new EditorControl (C:\Users\<USER>\.atom\packages\ide-haskell\lib\editor-control.coffee:74:41)
PluginManager.addController (C:\Users\<USER>\.atom\packages\ide-haskell\lib\plugin-manager.coffee:119:51)
PluginManager.controllerOnGrammar (C:\Users\<USER>\.atom\packages\ide-haskell\lib\plugin-manager.coffee:167:21)
<unknown> (C:\Users\<USER>\.atom\packages\ide-haskell\lib\plugin-manager.coffee:179:24)
Workspace.observeTextEditors (<embedded>:26156:15)
```

**Comment by lierdakil** [comment]
Should be fixed by the latest release (which basically just happened)

**Comment by RobertDober** [comment]
I still have this one, being directed to this issue by the _Report Issue_ button:

```
HTMLElement.rootElement - /private/var/folders/m_/wgnqsbwn4jb5nf4tdz7vxpsr0000gn/T/AppTranslocation/3FD37ADB-71F8-42DF-9FC4-083276592038/d/Atom 2.app/Contents/Resources/app.asar/src/text-editor-element.js:23:10
new EditorControl - /Users/robert/.atom/packages/ide-haskell/lib/editor-control.coffee:74:41
PluginManager.addController - /Users/robert/.atom/packages/ide-haskell/lib/plugin-manager.coffee:119:51
PluginManager.controllerOnGrammar - /Users/robert/.atom/packages/ide-haskell/lib/plugin-manager.coffee:167:21
<unknown> - /Users/robert/.atom/packages/ide-haskell/lib/plugin-manager.coffee:179:24
Workspace.observeTextEditors - <embedded>:26577:15
```

**Comment by lierdakil** [comment]
@RobertDober, you're on old ide-haskell release. Please update.

**Comment by RobertDober** [comment]
@lierdakil DONE thanks
